### ISSUE TITLE
gcc 4.7 compatibility

### ISSUE THREAD

**Issue by Burning-Daylight** [Amanieu/asyncplusplus#12]
The library does not compile with gcc-4.7.0 due to a "std::this_thread::yield()" problem which is known for the 4.7 version.
The error is:
>asyncplusplus/include/async++/task.h: In destructor ‘async::local_task<Sched, Func>::~local_task()’:
>asyncplusplus/include/async++/task.h:429:4: error: ‘yield’ is not a member of ‘std::this_thread’

**Comment by Amanieu** [comment]
Should be fixed by dae7ec0316dda4b2e67318b5daf305d2f7b57df6
